### PR TITLE
(update) Move initial time remaining to server side

### LINKED ISSUE #28: Payment expired on orders
Implement solution similar to [WP plugin](https://github.com/blockonomics/woocommerce-plugin/pull/201)

### PR DESCRIPTION
**Pull request by thisisayush**
Closes #28

### CODE REVIEW

**Review by DarrenWestwood — APPROVED** [review]

**Comment by DarrenWestwood** [comment]
The timestamp can also be removed from the websocket in case this is incorrect on the server:
https://github.com/blockonomics/easy-digital-downloads-plugin/blob/master/js/app.js#L96
https://github.com/blockonomics/woocommerce-plugin/blob/master/js/app.js#L58

**Comment by blockonomics** [comment]
I am not sure why still have concept of time_remaining here, in wordpress we removed this concept and always [reload timer from starting on page refresh](https://github.com/blockonomics/woocommerce-plugin/blob/5fddca933690682290866eaefb1a5023766eb822/js/app.js#L50)

**Comment by thisisayush** [comment]
Updated. @DarrenWestwood  @blockonomics

**Comment by blockonomics** [comment]
*timestamp* is used in various places in edd-blockonomics.php. It can be removed as it think it has no use

**Comment by thisisayush** [comment]
> _timestamp_ is used in various places in edd-blockonomics.php. It can be removed as it think it has no use

Done

**Pull request merged**
